name: ErrorEstimation
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - python=3.8.11
  - fenics=2019.1.0
  - scipy=1.7.0
  - numpy=1.21.1
  - matplotlib=3.4.2
  - dolfin-adjoint=2019.1.0
  - pip
  - pip:
      - https://github.com/milzj/FW4PDE/archive/refs/tags/v1.0.1.zip
