name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branchess:
      - "*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Lint with Ruff
        run: |
          python3 -m pip install --upgrade pip
          pip install ruff
          ruff --format=github --target-version=py38 .
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: 3.8.11
          auto-activate-base: false
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
